### ISSUE TITLE
Orange Pi 5 / 5B / 5 Plus - Microphone not working

### ISSUE THREAD

**Issue by ironiris** [Joshua-Riek/ubuntu-rockchip#198] opened 2023-06-12 03:15 UTC
In Orange Pi 5 Plus official Ubuntu,
There is a sound input option in Settings - Sound - Input - Input Device
but in Ubuntu-rockchip(orange pi 5 plus), there is nothing.

Thank you.

**Comment by Joshua-Riek** [comment] 2023-06-12 03:23
Hmmm, is this for HDMI IN? There should be HDMI0, HDMI1, HDMI-In, DP0, and ES8388 options available.

**Comment by Joshua-Riek** [comment] 2023-06-12 03:28
Or do you mean the microphone?

**Comment by arun-511** [comment] 2023-06-12 04:40
Yeah, there is no entry for the onboard microphone. The input field is empty until a device is added.

![Screenshot from 2023-06-12 10-03-23](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/37484578/05551ea6-7c47-43aa-83f2-eb877ad5af12)
![Screenshot from 2023-06-12 10-02-06](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/37484578/bd636533-c197-4e67-a09d-9d0d878a33a4)


But this is an excepted behaviour, right?

**Comment by ironiris** [comment] 2023-06-12 05:52
First of all, Orange Pi 5 Plus has a built-in microphone
and audio jack input*output.
If I run arecord command, The output is shown below.
`arecord -l
**** CAPTURE 하드웨어 장치 목록 ****
3 카드: rockchipes8388 [rockchip,es8388], 0 장치: dailink-multicodecs ES8323.7-0011-0 [dailink-multicodecs ES8323.7-0011-0]
  하위장치: 0/1
  하위장치 #0: subdevice #0
4 카드: rockchiphdmiin [rockchip,hdmiin], 0 장치: fddf8000.i2s-dummy_codec hdmiin-dc-0 [fddf8000.i2s-dummy_codec hdmiin-dc-0]
  하위장치: 1/1
  하위장치 #0: subdevice #0
`

However, if I try the command below to use video and sound together, it will say busy.
`gst-launch-1.0 v4l2src device=/dev/video0 io-mode=dmabuf ! video/x-raw,format=NV12,width=3840,height=2160,framerate=60/1 ! videoscale ! video/x-raw,width=2560,height=1440,framerate=60/1,key-int-max=4 ! mpph264enc ! h264parse ! mux. alsasrc device=hw:4,0 ! voaacenc bitrate=128000 ! aacparse ! mux. flvmux streamable=true name=mux ! queue ! rtmpsink location="rtmp://a.rtmp.youtube.com/live2/xy27-su6m-gs83-hkhj-036e"
Setting pipeline to PAUSED ...
ERROR: from element /GstPipeline:pipeline0/GstAlsaSrc:alsasrc0: Could not open audio device for recording. Device is being used by another application.
Additional debug info:
../ext/alsa/gstalsasrc.c(785): gst_alsasrc_open (): /GstPipeline:pipeline0/GstAlsaSrc:alsasrc0:
Device 'hw:4,0' is busy
ERROR: pipeline doesn't want to preroll.
Failed to set pipeline to PAUSED.
Setting pipeline to NULL ...
Freeing pipeline ...`

**Comment by Joshua-Riek** [comment] 2023-06-12 19:04
I did a quick test using an old hack of alsa-ucm-conf that I used a while ago for the Opi5 audio (no longer used because it's a hack and had some other issues). The microphone is detected on the Opi5 / 5B but not the Opi5 Plus. I will need to look into this more.

**Comment by njvergaraa** [comment] 2023-06-21 22:39
With headphones plugged into the jack on PI5 Plus no sound is played either. In the PI5a there are no problems, everything is ok.

Could it be part of the same bug?

**Comment by Joshua-Riek** [comment] 2023-06-21 22:54
Most likely. There are some audio configs from OrangePi that I need to play with. I have not had much time in the past few days, and work has been very busy. Thanks for letting me know the audio jack also has an issue, I would not have thought to test it.

**Comment by Joshua-Riek** [comment] 2023-06-22 02:08
I did a quick test with my old [v1.13](https://github.com/Joshua-Riek/ubuntu-rockchip/releases/tag/v1.13) release, and the microphone and audio jack both work. I will need to re-work a few things to fix this.

**Comment by ironiris** [comment] 2023-06-22 02:40
It would be nice to be able to hear the sound coming in through the HDMI IN as well.
Is there any way to do this?

**Comment by Joshua-Riek** [comment] 2023-06-22 03:16
I don't know. I need time to reverse engineer how Orange Pi has their sound system setup in their distro.

**Comment by cantalupo555** [comment] 2023-06-25 00:34
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/12485871/7ddef37a-d0fb-419b-8870-0ec7b74f6c2c)

@Joshua-Riek Here the problem is solved.

**Comment by Joshua-Riek** [comment] 2023-06-25 00:50
Wow! How was it solved???

**Comment by cantalupo555** [comment] 2023-06-25 00:55
> Wow! How was it solved???

Previously had this problem that was reported.
Nowadays my INPUT works both in Armbian and Ubuntu.
I didn't have to make any changes.

**Comment by njvergaraa** [comment] 2023-06-25 01:46
> > Wow! How was it solved???
> 
> Previously had this problem that was reported. Nowadays my INPUT works both in Armbian and Ubuntu. I didn't have to make any changes.
> 
> *Latest versions of the system (kernel).

@cantalupo555 How did you update the kernel ?... an apt upgrade does not bring me anything

**Comment by cantalupo555** [comment] 2023-06-25 11:24
> @cantalupo555 How did you update the kernel ?... an apt upgrade does not bring me anything

It was necessary to reinstall the operating system to the latest available version.

https://github.com/Joshua-Riek/ubuntu-rockchip/releases
or
https://www.armbian.com/orangepi-5/

**Comment by Joshua-Riek** [comment] 2023-06-25 16:36
This is very weird, and I have not updated anything to fix this.

**Comment by cantalupo555** [comment] 2023-06-26 12:11
> This is very weird, and I have not updated anything to fix this.

Yes, I'm just using the latest kernel version you implemented.
Problem here has been resolved.

**Comment by cantalupo555** [comment] 2023-06-27 14:27
Telegram
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/12485871/e0ab13ee-98c6-4d3c-a75f-66a6580ef5db)

Discord
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/12485871/0cb13855-9c42-48aa-b814-1959d9d09353)

**Comment by njvergaraa** [comment] 2023-06-28 20:42
@Joshua-Riek Work OK... Mic and Headset. Thanks!!!

**Comment by Joshua-Riek** [comment] 2023-06-28 21:03
Oh, I was confused, I thought this was for the on-board microphone for some reason haha. But yes the audio jack is now fixed and audio input including headset and microphones will now work.

**Closed by Joshua-Riek** 2023-06-28 21:03 UTC
Labels: bug

**Comment by bmecdev** [comment] 2023-07-05 00:28
![image](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/49051637/9b84a4b8-c275-4558-b574-2aeb480c8a95)
no input device on orange pi 5, the onboard microphone is not detect.
