### ISSUE TITLE
Youtube videos are green screen

### ISSUE THREAD

**Issue by Ukhupacha** [Joshua-Riek/ubuntu-rockchip#440] opened 2023-11-01 18:12 UTC
I'm using an Orange Pi 5, I update the version to 1.29.
Whenever I try to play a video from Youtube, the sound works but the video turns to a green screen
![Captura desde 2023-11-01 13-06-13](https://github.com/Joshua-Riek/ubuntu-rockchip/assets/5978666/4c52a4c2-c86e-476c-b733-86371a21a280)

> chromium-browser 
[4638:4638:1101/130507.812021:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[4681:4681:1101/130507.885169:ERROR:gl_display.cc(520)] EGL Driver message (Error) eglQueryDeviceAttribEXT: eglQueryDeviceAttribEXT
[4681:4681:1101/130507.885285:ERROR:gl_angle_util_vulkan.cc(189)] Failed to retrieve vkGetInstanceProcAddr
[4681:4681:1101/130507.885339:ERROR:vulkan_instance.cc(91)] Failed to get vkGetInstanceProcAddr pointer from ANGLE.
Failed to query video capabilities: Función ioctl no apropiada para el dispositivo

This is the log I have from running chromium on terminal

**Comment by Penguinator3000** [comment] 2023-11-02 18:29
Same happening to me. It is a great OS but has some playback issues... @Joshua-Riek what can we do?

**Comment by Joshua-Riek** [comment] 2023-11-02 18:33
I forgot the details but I'm pretty sure this can't be fixed. It does not support specific video playback resolutions.

**Comment by Penguinator3000** [comment] 2023-11-05 17:36
Yeah. Sometimes 720p video does not work, for me, 1080p works just fine.

**Comment by Joshua-Riek** [comment] 2023-11-05 17:38
Closing as duplicate of https://github.com/Joshua-Riek/ubuntu-rockchip/issues/270

**Closed by Joshua-Riek** 2023-11-05 17:38 UTC
Labels: bug
